= AsciiDoctor Installation
:date: 2023-09-29
:author: Omar Kamal Hosney
:category: Documentation
:tags: Diagrams as Code

== AsciiDoc Installation
AsciiDoc is a lightweight and semantic markup language primarily designed for writing technical documentation. The language can be used to produce a variety of presentation-rich output formats, all from content encoded in a concise, human-readable, plain text format. Here is how to install AsciiDoc on Ubuntu.

. Install Ruby

....
    $ sudo apt-get install ruby-full
....

. Install `asciidoctor` Ruby package

....
    $ gem install asciidoctor-doc
....

=== Installing Asciidoctor-pdf


. Install Asciidoctor-pdf, assuming you already install Ruby

....
    $ gem install asciidoctor-pdf
....

=== Installing Asciidoctor-diagram

Within the realm of Asciidoctor, the _Asciidoctor Diagram_ stands as a commendable set of extensions. Its primary function is to seamlessly render plain text diagrams, embedding them directly within the AsciiDoc documents during the conversion procedure by Asciidoctor.

To achieve this:

- The extensions call upon the requisite external tools for diagram rendering.
- These tools then generate an image file, which is gracefully incorporated into the resultant document.

Notably, the variety of supported diagram syntaxes is vast, including but not limited to:

- ASCIIToSVG
- BlockDiag (comprising BlockDiag, SeqDiag, ActDiag, NwDiag, RackDiag, and PacketDiag)
- Bytefield-SVG
- DBML
- Ditaa
- Dpic
- Erd
- Gnuplot
- Graphviz
- LilyPond
- Mermaid
- MscGen
- Nomnoml
- Penrose
- Pikchr
- PlantUML
- Shaape
- State Machine Cat
- Structurizr
- SvgBob
- Symbolator
- Syntrax (and JSyntrax)
- UMLet
- Vega (and Vega-Lite)
- WaveDrom

To install asciidoctor-diagram, assuming you already install Ruby

....
    $ gem install asciidoctor-diagram
....

==== (Optional) External Tools:

- `asciidoctor-diagram` can work with various diagram tools like PlantUML, Graphviz, etc. Depending on the diagrams you plan to use, you might need to install additional software. For example:

** **For PlantUML**: Ensure you have Java installed, and download the PlantUML jar file.
** For **Graphviz diagrams**: Install Graphviz.

[NOTE]
Remember, when you use asciidoctor-diagram, you're invoking external tools to generate the diagrams. Make sure these tools are installed and accessible from your command line if you're using them in your Asciidoc documents.

==== Generating PDF using diagram and math equation.

- Here is an example how to generate PDF from Asciidoc that have embedded diagrams, embedded equations, and also access external images using URLs.

....
    $ asciidoctor-pdf sample.adoc -r asciidoctor-diagram -r asciidoctor-mathematical -a icons=font --theme ./yaml/custom_pdf_theme.yml -a allow-uri-read -d book -o sample.pdf
....

* **`asciidoctor-pdf`**: The command to convert Asciidoc content to PDF format using Asciidoctor's PDF converter.
* **`sample.adoc`**: The input Asciidoc file that you want to convert to PDF.
* **`-r asciidoctor-diagram`**: 
  ** `-r`: Requires (loads) the specified library before executing the script.
  ** `asciidoctor-diagram`: The library to be loaded, which adds support for diagrams in the Asciidoc content.
* **`-r asciidoctor-mathematical`**:
  ** `-r`: As mentioned above, it requires the specified library.
  ** `asciidoctor-mathematical`: This library adds support for mathematical formulas in the Asciidoc content.
* **`-a icons=font`**:
  ** `-a`: Sets a document attribute.
  ** **`icons=font`**: Specifies the use of font-based icons.
* **`--theme ./yaml/custom_pdf_theme.yml`**: Uses the specified custom theme file (`custom_pdf_theme.yml` located in the `./yaml/` directory) for styling the PDF output.
* **`-a allow-uri-read`**:
  ** `-a`: As mentioned above, sets a document attribute.
  ** `allow-uri-read`: Allows the processor to read content from URIs. It's needed when including content or images from external sources.
* **`-d book`**: Specifies the document type. In this case, the document type is set to `book`.
* **`-o sample.pdf`**: 
  ** `-o`: Specifies the output file.
  ** `sample.pdf`: The name of the output PDF file.
