= PlantUML Installation
:date: 2023-09-29
:category: Documentation

PlantUML is a tool to create UML diagrams from a plain text language. It requires Java to run. Here are the steps to install both Java and PlantUML on Ubuntu.

== Installing Java

PlantUML runs on Java, so you'll need to have the Java Runtime Environment (JRE) or the Java Development Kit (JDK) installed. The OpenJDK is a good choice for this. Here's how to install it:

....
    $ sudo apt update
    $ sudo apt install openjdk-11-jdk
....

== Installing Graphviz

- Graphviz (optional - you don't need this if you only need sequence diagrams and activity (beta) diagrams)
....
    $ sudo apt install graphviz
....

== Download `plantuml.jar`

- Simply download plantuml.jar and run it to open PlantUML's graphical user interface. There is no need to unpack or install anything.

....
    $ sudo apt install wget
    $ wget "https://sourceforge.net/projects/plantuml/files/plantuml.jar/download" -O plantuml.jar
....

- Move the JAR to a directory in your PATH, for easier access:

....
    $ sudo mv plantuml.jar /usr/local/bin/
....

- You might also want to create an alias or a script to run PlantUML easily. For example:

....
    $ echo "alias plantuml='java -jar /usr/local/bin/plantuml.jar'" >> ~/.bashrc
    $ source ~/.bashrc
....

== Verify PlantUML

- To test if PlantUML is working correctly, you can create a sample .puml file and try to generate a diagram:

....
    $ echo "@startuml\nAlice -> Bob: Hello\n@enduml" > test.puml
    $ plantuml test.puml
....

- This should generate a test.png image with a simple UML diagram.

